# -*- coding: utf-8 -*-
"""
Fallback classification rules for the initial classification engine.

These rules assign a finv_category when the merchant knowledge base has a
keyword match but the merchant's category column is empty (99.87% of KB).

The rules are matched in priority order against:
1. The matched counterparty (merchant) name
2. The full transaction text

First match wins.  Categories are grouped for readability but order within
each group is chosen so more specific / less ambiguous patterns fire first.

At import time the rules are compiled into per-category combined regexes
(COMPILED_FALLBACK / COMPILED_ENT_REFINEMENT) for ~50× performance.
"""

from __future__ import annotations

import re
from collections import OrderedDict


# Priority-ordered regex -> category mapping.
# Rules are matched in order against (1) counterparty name, then (2) transaction text.
# First match wins.  Order matters: more specific / less ambiguous patterns first.
#
# Categories are grouped for readability but the order within each group is
# carefully chosen so more specific patterns match before broader ones.
FALLBACK_RULES: list[tuple[str, str]] = [
    # =========================================================================
    # Gambling — branded operators first (very high precision, low ambiguity)
    # =========================================================================
    (r"\bSPORTSBET\b", "Gambling"),
    (r"\bBET365\b", "Gambling"),
    (r"\bLADBROKES\b", "Gambling"),
    (r"\bBETFAIR\b", "Gambling"),
    (r"\bPOINTSBET\b", "Gambling"),
    (r"\bUNIBET\b", "Gambling"),
    (r"\bDRAFTKINGS\b", "Gambling"),
    (r"\bTAB\b", "Gambling"),
    (r"\bTATTSBET\b", "Gambling"),
    (r"\bTATTS\s+LOTTO\b", "Gambling"),
    (r"\bTATTS\s+ONLINE\b", "Gambling"),
    (r"\bTATTERSALL\b", "Gambling"),
    (r"\bNEDS\b", "Gambling"),
    (r"\bBLUEBET\b", "Gambling"),
    (r"\bPLAYUP\b", "Gambling"),
    (r"\bPALMERBET\b", "Gambling"),
    (r"\bBETR\b", "Gambling"),
    (r"\bBOSSBET\b", "Gambling"),
    (r"\bCLASSICBET\b", "Gambling"),
    (r"\bBETCHAIN\b", "Gambling"),
    (r"\bMADBOOKIE\b", "Gambling"),
    (r"\bTOPBETTA\b", "Gambling"),
    (r"\bTABCORP\b", "Gambling"),
    (r"\bLOTTO\b", "Gambling"),
    (r"\bOZLOTTO\b", "Gambling"),
    (r"\bPOWERBALL\b", "Gambling"),
    (r"\bKENO\b", "Gambling"),
    (r"\bGAMMA\s+SERVICES\b", "Gambling"),
    (r"\bKNGSWN\b", "Gambling"),
    (r"\bKNWOU\b", "Gambling"),
    (r"\bVXTRX\b", "Gambling"),
    (r"\bPOKER\b", "Gambling"),
    (r"\bPOKIES\b", "Gambling"),
    # =========================================================================
    # Travel — airlines, OTAs, accommodation brands (before Dining Out to
    # prevent HOTEL-type matches from capturing genuine travel bookings)
    # =========================================================================
    (r"\bQANTAS\s+(AIRWAYS|FREQUENT|FLIGHT|AIRLINE)\b", "Travel"),
    (r"\bJETSTAR\s+AIR", "Travel"),
    (r"\bJETSTAR\b", "Travel"),
    (r"\bVIRGIN\s+AUSTRALIA\b", "Travel"),
    (r"\bVIRGIN\s+BLUE\b", "Travel"),
    (r"\bREX\s+AIRLINES\b", "Travel"),
    (r"\bAIR\s+NEW\s+ZEALAND\b", "Travel"),
    (r"\bSINGAPORE\s+AIRLINES\b", "Travel"),
    (r"\bEMIRATES\s+AIRLINE\b", "Travel"),
    (r"\bCATHAY\s+PACIFIC\b", "Travel"),
    (r"\bAIRASIA\b", "Travel"),
    (r"\bFLIGHT\s+CENTRE\b", "Travel"),
    (r"\bBOOKING\s*\.?\s*COM\b", "Travel"),
    (r"\bEXPEDIA\b", "Travel"),
    (r"\bWOTIF\b", "Travel"),
    (r"\bLAST\s*MINUTE\b", "Travel"),
    (r"\bAGODA\b", "Travel"),
    (r"\bTRIVAGO\b", "Travel"),
    (r"\bAIRBNB\b", "Travel"),
    (r"\bSTAYZ\b", "Travel"),
    (r"\bWEBJET\b", "Travel"),
    (r"\bEDREAMS\b", "Travel"),
    (r"\bCARNIVAL\s+PL[CT]\b", "Travel"),
    (r"\bPRINCESS\s+CRUISES\b", "Travel"),
    (r"\bROYAL\s+CARIBBEAN\b", "Travel"),
    (r"\bP[&]O\s+CRUISES\b", "Travel"),
    (r"\bBRISBANE\s+AIRPORT\b", "Travel"),
    (r"\bSYDNEY\s+AIRPORT\b", "Travel"),
    (r"\bMELBOURNE\s+AIRPORT\b", "Travel"),
    (r"\bPERTH\s+AIRPORT\b", "Travel"),
    (r"\bHOSTEL\b", "Travel"),
    (r"\bBACKPACKERS\b", "Travel"),
    (r"\bCARAVAN\s+PARK\b", "Travel"),
    (r"\bHOLIDAY\s+PARK\b", "Travel"),
    # =========================================================================
    # Groceries — supermarkets, bottle shops, markets, convenience stores
    # =========================================================================
    (r"\bWOOLWORTHS\b", "Groceries"),
    (r"\bCOLES\b", "Groceries"),
    (r"\bCOLES\s+EXPRESS\b", "Groceries"),
    (r"\bBWS\b", "Groceries"),
    (r"\bALDI\b", "Groceries"),
    (r"\bIGA\b", "Groceries"),
    (r"\bFOODWORKS\b", "Groceries"),
    (r"\bFOODLAND\b", "Groceries"),
    (r"\bDRAKES\b", "Groceries"),
    (r"\bRITCHIES\b", "Groceries"),
    (r"\bSUPA\s*IGA\b", "Groceries"),
    (r"\bFREE\s+CHOICE\b", "Groceries"),
    (r"\bLIQUORLAND\b", "Groceries"),
    (r"\bDAN\s+MURPHY\b", "Groceries"),
    (r"\bFIRST\s+CHOICE\s+LIQUOR\b", "Groceries"),
    (r"\bVINTAGE\s+CELLARS\b", "Groceries"),
    (r"\bBOTTLE\s*[ -]?\s*O\b", "Groceries"),
    (r"\bBOTTLE\s+SHOP\b", "Groceries"),
    (r"\bCELLARBRATIONS\b", "Groceries"),
    (r"\bTHIRSTY\s+CAMEL\b", "Groceries"),
    (r"\bLIQUOR\s*MART\b", "Groceries"),
    (r"\bLIQUOR\s*LAND\b", "Groceries"),
    (r"\bSPAR\b", "Groceries"),
    (r"\bSUPABARN\b", "Groceries"),
    (r"\bHARRIS\s+FARM\b", "Groceries"),
    (r"\bFRUIT\s+MARKET\b", "Groceries"),
    (r"\bVEGETABLE\s+MARKET\b", "Groceries"),
    (r"\bFARMERS\s+MARKET\b", "Groceries"),
    (r"\bORGANIC\s+MARKET\b", "Groceries"),
    (r"\bCONVENIENCE\s+STORE\b", "Groceries"),
    (r"\bCONVENIENCE\s+SHOP\b", "Groceries"),
    (r"\bCORNER\s+STORE\b", "Groceries"),
    (r"\bMILK\s*BAR\b", "Groceries"),
    (r"\bDELICATESSEN\b", "Groceries"),
    (r"\bBUTCHER\b", "Groceries"),
    (r"\bBAKERY\b", "Groceries"),
    (r"\bBAKEHOUSE\b", "Groceries"),
    (r"\bFRUIT\s+AND\s+VEG\b", "Groceries"),
    (r"\bGROCER\b", "Groceries"),
    (r"\bGROCERY\b", "Groceries"),
    (r"\bSUPERMARKET\b", "Groceries"),
    (r"\bSEAFOOD\s+MARKET\b", "Groceries"),
    (r"\bFRESH\s+FOOD\b", "Groceries"),
    (r"\bFRESH\s+PRODUCE\b", "Groceries"),
    (r"\bFISH\s+MARKET\b", "Groceries"),
    (r"\bMEAT\s+MARKET\b", "Groceries"),
    (r"\bPOULTRY\b", "Groceries"),
    (r"\bTOBACCONIST\b", "Groceries"),
    (r"\bEZY\s*MART\b", "Groceries"),
    (r"\bNIGHT\s*OWL\b", "Groceries"),
    (r"\bNEWSAGENCY\b", "Groceries"),
    (r"\bCIGAR\b", "Groceries"),
    (r"\bVAPE\b", "Groceries"),
    (r"\bTSG\b", "Groceries"),
    (r"\bSMOKEMART\b", "Groceries"),
    (r"\bC[O0]CA[ -]?COLA\b", "Groceries"),
    # =========================================================================
    # Dining Out — restaurants, pubs, cafes, fast-food, food delivery
    # =========================================================================
    # -- food delivery platforms (very specific, before generic patterns) --
    (r"\bUBER\s*[ -]?\s*EATS\b", "Dining Out"),
    (r"\bDOORDASH\b", "Dining Out"),
    (r"\bMENULOG\b", "Dining Out"),
    (r"\bDELIVEROO\b", "Dining Out"),
    (r"\bEASI\s+(?:DELIVERY|FOOD)\b", "Dining Out"),
    # -- fast-food chains (high precision) --
    (r"\bMCDONALD'?S?\b", "Dining Out"),
    (r"\bKFC\b", "Dining Out"),
    (r"\bSUBWAY\b", "Dining Out"),
    (r"\bHUNGRY\s+JACK'?S?\b", "Dining Out"),
    (r"\bDOMINO'?S?\b", "Dining Out"),
    (r"\bGRILL'?D\b", "Dining Out"),
    (r"\bNANDO'?S?\b", "Dining Out"),
    (r"\bGUZMAN\s+Y\s+GOMEZ\b", "Dining Out"),
    (r"\bZAMBRERO\b", "Dining Out"),
    (r"\bRED\s*ROOSTER\b", "Dining Out"),
    (r"\bOJOP\b", "Dining Out"),
    (r"\bCHICKEN\s+TREAT\b", "Dining Out"),
    (r"\bOPORTO\b", "Dining Out"),
    (r"\bTACO\s+BELL\b", "Dining Out"),
    (r"\bCARL'?S?\s+JR\b", "Dining Out"),
    (r"\bWENDY'?S?\b", "Dining Out"),
    (r"\bJIMMY\s+JOHNS\b", "Dining Out"),
    (r"\bCHIPOTLE\b", "Dining Out"),
    (r"\bPIZZA\s+HUT\b", "Dining Out"),
    (r"\bPIZZA\b", "Dining Out"),
    (r"\bCRUST\s+PIZZA\b", "Dining Out"),
    (r"\bROLL'?D\b", "Dining Out"),
    (r"\bFISH\s+AND\s+CHIPS\b", "Dining Out"),
    (r"\bFISH\s*&\s*CHIPS\b", "Dining Out"),
    (r"\bCHICKEN\s+SHOP\b", "Dining Out"),
    (r"\bCHICKEN\s+BAR\b", "Dining Out"),
    (r"\bCHARCOAL\s+CHICKEN\b", "Dining Out"),
    (r"\bROAST\s+CHICKEN\b", "Dining Out"),
    (r"\bFRIED\s+CHICKEN\b", "Dining Out"),
    (r"\bHOT\s+CHICKEN\b", "Dining Out"),
    # -- cafe / coffee chains --
    (r"\bSTARBUCKS\b", "Dining Out"),
    (r"\bCOFFEE\s+CLUB\b", "Dining Out"),
    (r"\bGLORIA\s+JEAN'?S?\b", "Dining Out"),
    (r"\bZARRAFFA'?S?\s+COFFEE\b", "Dining Out"),
    (r"\bBOOST\s+JUICE\b", "Dining Out"),
    (r"\bTOP\s+JUICE\b", "Dining Out"),
    (r"\bBOOST\b", "Dining Out"),
    (r"\bCHATIME\b", "Dining Out"),
    (r"\bGONG\s+CHA\b", "Dining Out"),
    (r"\bSHARETEA\b", "Dining Out"),
    (r"\bKUNG\s+FU\s+TEA\b", "Dining Out"),
    (r"\bGONGCHA\b", "Dining Out"),
    (r"\bCOCO\s+FRESH\b", "Dining Out"),
    (r"\bJUICE\s+BAR\b", "Dining Out"),
    (r"\bSMOOTHIE\b", "Dining Out"),
    # -- drink / dessert --
    (r"\bBOBA\b", "Dining Out"),
    (r"\bBUBBLE\s+TEA\b", "Dining Out"),
    (r"\bPEARL\s+TEA\b", "Dining Out"),
    (r"\bICE\s+CREAM\b", "Dining Out"),
    (r"\bGELATO\b", "Dining Out"),
    (r"\bGELATISSIMO\b", "Dining Out"),
    (r"\bMESSINA\b", "Dining Out"),
    (r"\bDONUT\b", "Dining Out"),
    (r"\bDOUGHNUT\b", "Dining Out"),
    (r"\bKRISPY\s+KREME\b", "Dining Out"),
    (r"\bDONUT\s+KING\b", "Dining Out"),
    (r"\bYOGURT\s+LAND\b", "Dining Out"),
    (r"\bYO[ -]?CHI\b", "Dining Out"),
    (r"\bFROZEN\s+YOGURT\b", "Dining Out"),
    (r"\bDESSERT\b", "Dining Out"),
    (r"\bPATISSERIE\b", "Dining Out"),
    (r"\bBAKE\s+SHOP\b", "Dining Out"),
    (r"\bPASTRY\b", "Dining Out"),
    (r"\bCROISSANT\b", "Dining Out"),
    # -- pub / hotel dining (specific multi-word patterns to avoid Travel false positives) --
    (r"\bPUB\s+AND\s+HOTEL\b", "Dining Out"),
    (r"\bHOTEL\s+MOTEL\b", "Dining Out"),
    (r"\bSPORTS\s+BAR\b", "Dining Out"),
    (r"\bBAR\s+AND\s+GRILL\b", "Dining Out"),
    (r"\bBAR\s+&\s+GRILL\b", "Dining Out"),
    (r"\bBISTRO\b", "Dining Out"),
    (r"\bBRASSERIE\b", "Dining Out"),
    (r"\bTAVERN\b", "Dining Out"),
    (r"\bROADHOUSE\b", "Dining Out"),
    (r"\bSURF\s+CLUB\b", "Dining Out"),
    (r"\bBOWLS\s+CLUB\b", "Dining Out"),
    (r"\bBOWLING\s+CLUB\b", "Dining Out"),
    (r"\bLEAGUES\s+CLUB\b", "Dining Out"),
    (r"\bRSL\s+CLUB\b", "Dining Out"),
    (r"\bRSL\b", "Dining Out"),
    (r"\bWORKERS\s+CLUB\b", "Dining Out"),
    (r"\bSPORTING\s+CLUB\b", "Dining Out"),
    (r"\bSPORTS\s+CLUB\b", "Dining Out"),
    (r"\bRECREATION\s+CLUB\b", "Dining Out"),
    (r"\bGOLF\s+CLUB\b", "Gyms and other memberships"),
    (r"\bCOUNTRY\s+CLUB\b", "Dining Out"),
    (r"\bDIGGERS\s+CLUB\b", "Dining Out"),
    (r"\bSERVICES\s+CLUB\b", "Dining Out"),
    (r"\bMEMORIAL\s+CLUB\b", "Dining Out"),
    (r"\bEX[ -]?SERVICES\s+CLUB\b", "Dining Out"),
    (r"\bYOGA\s+BAR\b", "Dining Out"),
    (r"\bWINE\s+BAR\b", "Dining Out"),
    (r"\bBEER\s+GARDEN\b", "Dining Out"),
    (r"\bBREWERY\b", "Dining Out"),
    (r"\bBREWHOUSE\b", "Dining Out"),
    (r"\bDISTILLERY\b", "Dining Out"),
    (r"\bCELLAR\s+DOOR\b", "Dining Out"),
    (r"\bVINEYARD\b", "Dining Out"),
    (r"\bWINERY\b", "Dining Out"),
    # -- restaurant / eatery types --
    (r"\bRESTAURANT\b", "Dining Out"),
    (r"\bEATERY\b", "Dining Out"),
    (r"\bDINER\b", "Dining Out"),
    (r"\bCANTEEN\b", "Dining Out"),
    (r"\bCAFETERIA\b", "Dining Out"),
    (r"\bCAFE\b", "Dining Out"),
    (r"\bCOFFEE\b", "Dining Out"),
    (r"\bESPRESSO\b", "Dining Out"),
    (r"\bLUNCH\s+BAR\b", "Dining Out"),
    (r"\bSNACK\s+BAR\b", "Dining Out"),
    (r"\bTAKE\s*AWAY\b", "Dining Out"),
    (r"\bTAKEAWAY\b", "Dining Out"),
    (r"\bFOOD\s+COURT\b", "Dining Out"),
    (r"\bFOOD\s+BAR\b", "Dining Out"),
    (r"\bFOOD\s+TRUCK\b", "Dining Out"),
    (r"\bCATERING\b", "Dining Out"),
    (r"\bBAKERS?\s+DELIGHT\b", "Dining Out"),
    (r"\bBREAD\s+SHOP\b", "Dining Out"),
    (r"\bBREAD\s+AND\b", "Dining Out"),
    (r"\bSANDWICH\b", "Dining Out"),
    (r"\bWRAP\s+BAR\b", "Dining Out"),
    (r"\bSALAD\s+BAR\b", "Dining Out"),
    (r"\bBUFFET\b", "Dining Out"),
    (r"\bBANQUET\b", "Dining Out"),
    # -- cuisine keywords (commonly appear in restaurant names) --
    (r"\bSUSHI\b", "Dining Out"),
    (r"\bNOODLE\b", "Dining Out"),
    (r"\bRAMEN\b", "Dining Out"),
    (r"\bPHO\b", "Dining Out"),
    (r"\bVIETNAMESE\b", "Dining Out"),
    (r"\bTHAI\b", "Dining Out"),
    (r"\bCHINESE\s+FOOD\b", "Dining Out"),
    (r"\bCHINESE\s+REST\b", "Dining Out"),
    (r"\bINDIAN\s+REST\b", "Dining Out"),
    (r"\bINDIAN\s+CUISINE\b", "Dining Out"),
    (r"\bCURRY\b", "Dining Out"),
    (r"\bINDIAN\b", "Dining Out"),
    (r"\bJAPANESE\b", "Dining Out"),
    (r"\bKOREAN\b", "Dining Out"),
    (r"\bITALIAN\b", "Dining Out"),
    (r"\bMEXICAN\b", "Dining Out"),
    (r"\bTURKISH\b", "Dining Out"),
    (r"\bLEBANESE\b", "Dining Out"),
    (r"\bGREEK\b", "Dining Out"),
    (r"\bMEDITERRANEAN\b", "Dining Out"),
    (r"\bYUM\s+CHA\b", "Dining Out"),
    (r"\bDUMPLING\b", "Dining Out"),
    (r"\bDIM\s+SIM\b", "Dining Out"),
    (r"\bKEBAB\b", "Dining Out"),
    (r"\bBURGER\b", "Dining Out"),
    (r"\bBURGERS\b", "Dining Out"),
    (r"\bSTEAK\s+HOUSE\b", "Dining Out"),
    (r"\bSTEAKHOUSE\b", "Dining Out"),
    (r"\bSMOKEHOUSE\b", "Dining Out"),
    (r"\bBBQ\b", "Dining Out"),
    (r"\bBARBEQUE\b", "Dining Out"),
    (r"\bBARBECUE\b", "Dining Out"),
    (r"\bSEAFOOD\s+REST\b", "Dining Out"),
    (r"\bOYSTER\b", "Dining Out"),
    (r"\bTAPAS\b", "Dining Out"),
    (r"\bPAELLA\b", "Dining Out"),
    (r"\bROTI\b", "Dining Out"),
    (r"\bSATAY\b", "Dining Out"),
    (r"\bLAKSA\b", "Dining Out"),
    (r"\bBANH\s+MI\b", "Dining Out"),
    # -- hotel dining (single-word match; broad but Travel patterns matched first) --
    (r"\bHOTEL\b", "Dining Out"),
    (r"\bMOTEL\b", "Dining Out"),
    (r"\bINN\b", "Dining Out"),
    (r"\bPUB\b", "Dining Out"),
    (r"\bBAR\b", "Dining Out"),
    (r"\bGRILL\b", "Dining Out"),
    # =========================================================================
    # Subscription TV / Streaming / Digital subscriptions
    # =========================================================================
    (r"\bNETFLIX\b", "Subscription TV"),
    (r"\bSTAN\b", "Subscription TV"),
    (r"\bSPOTIFY\b", "Subscription TV"),
    (r"\bDISNEY\s*[+]?\b", "Subscription TV"),
    (r"\bDISNEY\s+PLUS\b", "Subscription TV"),
    (r"\bDISNEYPLUS\b", "Subscription TV"),
    (r"\bAMAZON\s+PRIME\b", "Subscription TV"),
    (r"\bPRIME\s+VIDEO\b", "Subscription TV"),
    (r"\bAPPLE\s+TV\b", "Subscription TV"),
    (r"\bAPPLETV\b", "Subscription TV"),
    (r"\bBINGE\b", "Subscription TV"),
    (r"\bKAYO\b", "Subscription TV"),
    (r"\bFOXTEL\b", "Subscription TV"),
    (r"\bFETCH\s+TV\b", "Subscription TV"),
    (r"\bFETCH\b", "Subscription TV"),
    (r"\bHBO\s*MAX\b", "Subscription TV"),
    (r"\bHBOMAX\b", "Subscription TV"),
    (r"\bHUBBL\b", "Subscription TV"),
    (r"\bPARAMOUNT\s*[+]\b", "Subscription TV"),
    (r"\bBRITBOX\b", "Subscription TV"),
    (r"\bSCRIBD\b", "Subscription TV"),
    (r"\bAUDIBLE\b", "Subscription TV"),
    (r"\bYOUTUBE\s+PREMIUM\b", "Subscription TV"),
    (r"\bYOUTUBE\s+MUSIC\b", "Subscription TV"),
    (r"\bYOUTUBE\s+TV\b", "Subscription TV"),
    (r"\bGOOGLE\s+ONE\b", "Subscription TV"),
    (r"\bICLOUD\s*[+]\b", "Subscription TV"),
    (r"\bAPPLE\s+MUSIC\b", "Subscription TV"),
    (r"\bAPPLE\s+ARCADE\b", "Subscription TV"),
    (r"\bAPPLE\s+FITNESS\b", "Subscription TV"),
    (r"\bONLY\s*FANS\b", "Subscription TV"),
    (r"\bPATREON\b", "Subscription TV"),
    (r"\bSUBSTACK\b", "Subscription TV"),
    # =========================================================================
    # Health — pharmacy, medical, dental, allied health
    # =========================================================================
    (r"\bPHARMACY\b", "Health"),
    (r"\bCHEMIST\s+WAREHOUSE\b", "Health"),
    (r"\bCHEMIST\b", "Health"),
    (r"\bPRICELINE\s+PHARMACY\b", "Health"),
    (r"\bTERRY\s+WHITE\b", "Health"),
    (r"\bAMCAL\b", "Health"),
    (r"\bGUARDIAN\s+PHARMACY\b", "Health"),
    (r"\bDISCOUNT\s+DRUG\b", "Health"),
    (r"\bMEDICAL\s+CENTRE\b", "Health"),
    (r"\bMEDICAL\s+CENTER\b", "Health"),
    (r"\bMEDICAL\s+CLINIC\b", "Health"),
    (r"\bMEDICAL\s+PRACTICE\b", "Health"),
    (r"\bMEDICAL\s+GROUP\b", "Health"),
    (r"\bFAMILY\s+PRACTICE\b", "Health"),
    (r"\bGENERAL\s+PRACTICE\b", "Health"),
    (r"\bGP\s+CLINIC\b", "Health"),
    (r"\bHOSPITAL\b", "Health"),
    (r"\bAMBULANCE\b", "Health"),
    (r"\bDENTAL\b", "Health"),
    (r"\bDENTIST\b", "Health"),
    (r"\bORTHODONTIST\b", "Health"),
    (r"\bORTHODONTICS\b", "Health"),
    (r"\bENDODONTIC\b", "Health"),
    (r"\bOPTICAL\b", "Health"),
    (r"\bOPTOMETRIST\b", "Health"),
    (r"\bOPTIKA\b", "Health"),
    (r"\bOPHTHALMOLOG\b", "Health"),
    (r"\bPHYSIOTHERAPY\b", "Health"),
    (r"\bPHYSIO\b", "Health"),
    (r"\bCHIROPRACTIC\b", "Health"),
    (r"\bCHIRO\b", "Health"),
    (r"\bOSTEOPATH\b", "Health"),
    (r"\bPODIATRIST\b", "Health"),
    (r"\bPODIATRY\b", "Health"),
    (r"\bPSYCHOLOGIST\b", "Health"),
    (r"\bPSYCHIATRIST\b", "Health"),
    (r"\bPSYCHOLOGY\b", "Health"),
    (r"\bCOUNSELLING\b", "Health"),
    (r"\bCOUNSELING\b", "Health"),
    (r"\bTHERAPY\b", "Health"),
    (r"\bDERMATOLOG\b", "Health"),
    (r"\bCARDIOLOG\b", "Health"),
    (r"\bRADIOLOGY\b", "Health"),
    (r"\bPATHOLOGY\b", "Health"),
    (r"\bDIAGNOSTIC\b", "Health"),
    (r"\bSONOGRAPH\b", "Health"),
    (r"\bULTRASOUND\b", "Health"),
    (r"\bAUDIOLOGY\b", "Health"),
    (r"\bHEARING\s+CLINIC\b", "Health"),
    (r"\bHEARING\s+AID\b", "Health"),
    (r"\bRESMED\b", "Health"),
    (r"\bCPAP\b", "Health"),
    (r"\bSLEEP\s+APNOEA\b", "Health"),
    (r"\bSLEEP\s+APNEA\b", "Health"),
    (r"\bAMBOS\b", "Health"),
    (r"\bFIRST\s+AID\b", "Health"),
    (r"\bMASSAGE\b", "Health"),
    (r"\bREMEDIAL\b", "Health"),
    (r"\bACUPUNCTURE\b", "Health"),
    (r"\bNATUROPATH\b", "Health"),
    (r"\bNATUROPATHY\b", "Health"),
    (r"\bDIETITIAN\b", "Health"),
    (r"\bNUTRITION\b", "Health"),
    (r"\bSPEECH\s+PATHOLOG\b", "Health"),
    (r"\bOCCUPATIONAL\s+THERAP\b", "Health"),
    (r"\bADHERIS\s+HEALTH\b", "Health"),
    (r"\bMONTU\s+GROUP\b", "Health"),
    (r"\bINSTANTSCRIPTS\b", "Health"),
    (r"\bSCRIPTS\s+ONLINE\b", "Health"),
    (r"\bMEDADVISOR\b", "Health"),
    (r"\bPHARMACY\s+4\s+LESS\b", "Health"),
    (r"\bCHEMIST\s+OUTLET\b", "Health"),
    (r"\bSOUL\s+PATTINSON\b", "Health"),
    (r"\bBLOOMS\s+THE\s+CHEMIST\b", "Health"),
    # =========================================================================
    # Insurance — health, general, life insurance
    # =========================================================================
    (r"\bINSURANCE\b", "Insurance"),
    (r"\bMEDIBANK\b", "Insurance"),
    (r"\bBUPA\b", "Insurance"),
    (r"\bHCF\b", "Insurance"),
    (r"\bNIB\b", "Insurance"),
    (r"\bAHM\b", "Insurance"),
    (r"\bGMHBA\b", "Insurance"),
    (r"\bHBF\b", "Insurance"),
    (r"\bDEFENCE\s+HEALTH\b", "Insurance"),
    (r"\bGU\s+HEALTH\b", "Insurance"),
    (r"\bLATROBE\s+HEALTH\b", "Insurance"),
    (r"\bTEACHERS\s+HEALTH\b", "Insurance"),
    (r"\bPOLICE\s+HEALTH\b", "Insurance"),
    (r"\bCBHS\s+HEALTH\b", "Insurance"),
    (r"\bALLIANZ\b", "Insurance"),
    (r"\bAAMI\b", "Insurance"),
    (r"\bNRMA\b", "Insurance"),
    (r"\bQBE\b", "Insurance"),
    (r"\bRACQ\b", "Insurance"),
    (r"\bRAA\s+INSURANCE\b", "Insurance"),
    (r"\bRACT\b", "Insurance"),
    (r"\bRACV\b", "Insurance"),
    (r"\bRAC\b", "Insurance"),
    (r"\bSGIO\b", "Insurance"),
    (r"\bSGIC\b", "Insurance"),
    (r"\bBUDGET\s+DIRECT\b", "Insurance"),
    (r"\bPROGRESSIVE\b", "Insurance"),
    (r"\bYOUII?\b", "Insurance"),
    (r"\bSHANNON'?S?\b", "Insurance"),
    (r"\bAPIA\b", "Insurance"),
    (r"\bAUSTRALIAN\s+UNITY\b", "Insurance"),
    (r"\bREAL\s+INSURANCE\b", "Insurance"),
    (r"\bLIFE\s+INSURANCE\b", "Insurance"),
    (r"\bINCOME\s+PROTECTION\b", "Insurance"),
    (r"\bTPD\s+INSURANCE\b", "Insurance"),
    (r"\bTRAUMA\s+INSURANCE\b", "Insurance"),
    (r"\bHEALTH\s+INSURANCE\b", "Insurance"),
    (r"\bCAR\s+INSURANCE\b", "Insurance"),
    (r"\bHOME\s+INSURANCE\b", "Insurance"),
    (r"\bTRAVEL\s+INSURANCE\b", "Insurance"),
    (r"\bPET\s+INSURANCE\b", "Insurance"),
    (r"\bSUNCORP\s+(?:INSURANCE|WEALTH)\b", "Insurance"),
    (r"\bGENUS\s+(?:PRODUCT|LIFE)\b", "Insurance"),
    (r"\bCOVERMORE\b", "Insurance"),
    (r"\bSOUTHERN\s+CROSS\b", "Insurance"),
    # =========================================================================
    # Automotive — fuel, car service, parking, tolls
    # =========================================================================
    (r"\bUNITED\s+PETROLEUM\b", "Automotive"),
    (r"\bREDDY\s+EXPRESS\b", "Automotive"),
    (r"\bEG\s+GROUP\b", "Automotive"),
    (r"\b7[ -]?ELEVEN\b", "Automotive"),
    (r"\bBP\s+(?:SERVICE|PETROL|EXPRESS|SHOP|CONNECT)\b", "Automotive"),
    (r"\bBP\b", "Automotive"),
    (r"\bSHELL\s+(?:COLES\s+EXPRESS|SERVICE|PETROL)\b", "Automotive"),
    (r"\bSHELL\b", "Automotive"),
    (r"\bCALTEX\b", "Automotive"),
    (r"\bAMPOL\b", "Automotive"),
    (r"\bMOBIL\b", "Automotive"),
    (r"\bPUMA\s+ENERGY\b", "Automotive"),
    (r"\bFREEDOM\s+FUELS\b", "Automotive"),
    (r"\bSPEEDWAY\b", "Automotive"),
    (r"\bPETROL\b", "Automotive"),
    (r"\bSERVO\b", "Automotive"),
    (r"\bFUEL\b", "Automotive"),
    (r"\bDIESEL\b", "Automotive"),
    (r"\bGASOLINE\b", "Automotive"),
    (r"\bCAR\s+WASH\b", "Automotive"),
    (r"\bDOG\s+WASH\b", "Automotive"),
    (r"\bAUTO\s+REPAIR\b", "Automotive"),
    (r"\bCAR\s+REPAIR\b", "Automotive"),
    (r"\bCAR\s+SERVICE\b", "Automotive"),
    (r"\bMECHANICAL\s+REPAIR\b", "Automotive"),
    (r"\bMECHANICAL\b", "Automotive"),
    (r"\bTYRE\b", "Automotive"),
    (r"\bTIRE\b", "Automotive"),
    (r"\bTYRE\s+POWER\b", "Automotive"),
    (r"\bBOB\s+JANE\b", "Automotive"),
    (r"\bBEAUREPAIRES\b", "Automotive"),
    (r"\bJAX\s+TYRES\b", "Automotive"),
    (r"\bGOODYEAR\b", "Automotive"),
    (r"\bBRIDGESTONE\b", "Automotive"),
    (r"\bWINDSCREEN\b", "Automotive"),
    (r"\bOBRIEN\s+(?:GLASS|AUTO)\b", "Automotive"),
    (r"\bPANEL\s+BEATING\b", "Automotive"),
    (r"\bPANEL\s+BEATER\b", "Automotive"),
    (r"\bSMASH\s+REPAIR\b", "Automotive"),
    (r"\bEXHAUST\s+(?:CENTRE|CENTER)\b", "Automotive"),
    (r"\bEXHAUST\b", "Automotive"),
    (r"\bBRAKE\s+(?:SERVICE|REPAIR|SPECIALIST)\b", "Automotive"),
    (r"\bSUSPENSION\b", "Automotive"),
    (r"\bMUFFLER\b", "Automotive"),
    (r"\bRADIATOR\b", "Automotive"),
    (r"\bAUTOMOTIVE\b", "Automotive"),
    (r"\bAUTO\s+ELECTRIC\b", "Automotive"),
    (r"\bAUTO\s+PARTS\b", "Automotive"),
    (r"\bSUPER\s+CHEAP\s+AUTO\b", "Automotive"),
    (r"\bAUTOBARN\b", "Automotive"),
    (r"\bREPCO\b", "Automotive"),
    (r"\bBURS[O0]N\b", "Automotive"),
    (r"\bPARKING\b", "Automotive"),
    (r"\bSECURE\s+PARKING\b", "Automotive"),
    (r"\bWILSON\s+PARKING\b", "Automotive"),
    (r"\bCAR\s+PARK\b", "Automotive"),
    (r"\bLINKT\b", "Automotive"),
    (r"\bTOLL\b", "Automotive"),
    (r"\bEASTLINK\b", "Automotive"),
    (r"\bCITYLINK\b", "Automotive"),
    (r"\bTRANSPORT\s+FOR\s+NSW\b", "Transport"),
    # =========================================================================
    # Transport — public transport, ride-share, taxi
    # =========================================================================
    (r"\bTRANSPORTFORNSW\b", "Transport"),
    (r"\bTRANSPORT\s+FOR\s+NSW\b", "Transport"),
    (r"\bTRANSLINK\b", "Transport"),
    (r"\bMETRO\s+TAS\b", "Transport"),
    (r"\bMETRO\s+TRAINS\b", "Transport"),
    (r"\bMETRO\s+TICKET\b", "Transport"),
    (r"\bPTV\b", "Transport"),
    (r"\bDIDIMOBILITY\b", "Transport"),
    (r"\bDIDI\b", "Transport"),
    (r"\bOLAFARE\b", "Transport"),
    (r"\b13CABS\b", "Transport"),
    (r"\bCABCHARGE\b", "Transport"),
    (r"\bTAXI\b", "Transport"),
    (r"\bMYLI\b", "Transport"),
    (r"\bGOCATCH\b", "Transport"),
    (r"\bINGOGO\b", "Transport"),
    (r"\bSHENTON\b", "Transport"),
    (r"\bOPAL\s+CARD\b", "Transport"),
    (r"\bOPAL\b", "Transport"),
    (r"\bUBER(?!\s*[ -]?\s*EATS)\b", "Transport"),  # Uber ride, not Uber Eats
    (r"\bMYLI\b", "Transport"),
    (r"\bAUSTRALIAN\s+POSTAL\b", "Transport"),
    (r"\bAUSTRALIA\s+POST\b", "Transport"),
    (r"\bAUSPOST\b", "Transport"),
    (r"\bPOST\s+OFFICE\b", "Transport"),
    (r"\bQUEENSLAND\s+MOTORWAYS\b", "Transport"),
    (r"\bTOLLAUST\b", "Transport"),
    # =========================================================================
    # Utilities — electricity, gas, water
    # =========================================================================
    (r"\bORIGIN\s+ENERGY\b", "Utilities"),
    (r"\bENERGYAUSTRALIA\b", "Utilities"),
    (r"\bENERGY\s+AUSTRALIA\b", "Utilities"),
    (r"\bAGL\s+(?:ENERGY|ELECTRICITY)\b", "Utilities"),
    (r"\bAGL\b", "Utilities"),
    (r"\bSIMPLY\s+ENERGY\b", "Utilities"),
    (r"\bALINTA\s+ENERGY\b", "Utilities"),
    (r"\bPOWERSHOP\b", "Utilities"),
    (r"\bRED\s+ENERGY\b", "Utilities"),
    (r"\bMOMENTUM\s+ENERGY\b", "Utilities"),
    (r"\bSYDNEY\s+WATER\b", "Utilities"),
    (r"\bSYDNEY\s+WATER\b", "Utilities"),
    (r"\bURBAN\s+UTILITIES\b", "Utilities"),
    (r"\bYARRA\s+VALLEY\s+WATER\b", "Utilities"),
    (r"\bSA\s+WATER\b", "Utilities"),
    (r"\bWATER\s+CORP\b", "Utilities"),
    (r"\bUNITYWATER\b", "Utilities"),
    (r"\bQUEENSLAND\s+URBAN\b", "Utilities"),
    (r"\bELECTRICITY\b", "Utilities"),
    (r"\bENERGY\s+BILL\b", "Utilities"),
    (r"\bGAS\s+BILL\b", "Utilities"),
    (r"\bWATER\s+BILL\b", "Utilities"),
    (r"\bCOUNCIL\s+RATES\b", "Utilities"),
    (r"\bRATES\s+PAYMENT\b", "Utilities"),
    (r"\bGAS\s+COMPANY\b", "Utilities"),
    (r"\bPOWER\s+COMPANY\b", "Utilities"),
    (r"\bUTILITY\b", "Utilities"),
    (r"\bENERGY\b", "Utilities"),
    (r"\bWATER\s+RATES\b", "Utilities"),
    (r"\bELGAS\b", "Utilities"),
    (r"\bAPA\s+GROUP\b", "Utilities"),
    (r"\bFILL\s+N\s+GO\b", "Utilities"),
    # =========================================================================
    # Telecommunications — internet, mobile, phone
    # =========================================================================
    (r"\bTELSTRA\b", "Telecommunications"),
    (r"\bOPTUS\b", "Telecommunications"),
    (r"\bVODAFONE\b", "Telecommunications"),
    (r"\bBELONG\b", "Telecommunications"),
    (r"\bAMAYSIM\b", "Telecommunications"),
    (r"\bTPG\b", "Telecommunications"),
    (r"\bII?NET\b", "Telecommunications"),
    (r"\bAUSSIE\s+BROADBAND\b", "Telecommunications"),
    (r"\bSUPERLOOP\b", "Telecommunications"),
    (r"\bDODO\s+SERVICES\b", "Telecommunications"),
    (r"\bDODO\b", "Telecommunications"),
    (r"\bSPINTEL\b", "Telecommunications"),
    (r"\bEXETEL\b", "Telecommunications"),
    (r"\bMATES\s+COMMUNIC\b", "Telecommunications"),
    (r"\bPRIMUS\s+TELECOM\b", "Telecommunications"),
    (r"\bMOBILE\s+PHONE\b", "Telecommunications"),
    (r"\bBROADBAND\b", "Telecommunications"),
    (r"\bINTERNET\s+PROVIDER\b", "Telecommunications"),
    (r"\bTELECOM\b", "Telecommunications"),
    (r"\bTELECOMMUNICATION\b", "Telecommunications"),
    # =========================================================================
    # Retail — clothing, electronics, homewares, sports, specialty
    # =========================================================================
    (r"\bCOTTON\s+ON\b", "Retail"),
    (r"\bOFFICEWORKS\b", "Retail"),
    (r"\bJB\s+HI[ -]?FI\b", "Retail"),
    (r"\bGLASSONS\b", "Retail"),
    (r"\bMECCA\s+(?:BRANDS|MAXIMA|COSMETICA)\b", "Retail"),
    (r"\bMECCA\b", "Retail"),
    (r"\bSEPHORA\b", "Retail"),
    (r"\bREBEL\s+SPORT\b", "Retail"),
    (r"\bREBEL\b", "Retail"),
    (r"\bLOVISA\b", "Retail"),
    (r"\bSPORTSGIRL\b", "Retail"),
    (r"\bCONNOR\s+CLOTHING\b", "Retail"),
    (r"\bCONNOR\b", "Retail"),
    (r"\bJAY\s*JAYS?\b", "Retail"),
    (r"\bPETER\s+ALEXANDER\b", "Retail"),
    (r"\bSMIGGLE\b", "Retail"),
    (r"\bTYPO\b", "Retail"),
    (r"\bBEST\s+AND\s+LESS\b", "Retail"),
    (r"\bTHE\s+ICONIC\b", "Retail"),
    (r"\bASOS\b", "Retail"),
    (r"\bSHEIN\b", "Retail"),
    (r"\bSPENDLESS\s+SHOES\b", "Retail"),
    (r"\bBRAS\s+N\s+THINGS\b", "Retail"),
    (r"\bPEPPERMAYO\b", "Retail"),
    (r"\bH[&]M\b", "Retail"),
    (r"\bH[&]M\s+HENNES\b", "Retail"),
    (r"\bUNIQLO\b", "Retail"),
    (r"\bZARA\b", "Retail"),
    (r"\bFOREVER\s+NEW\b", "Retail"),
    (r"\bWITCHERY\b", "Retail"),
    (r"\bCOUNTRY\s+ROAD\b", "Retail"),
    (r"\bTRENERY\b", "Retail"),
    (r"\bPORTMANS\b", "Retail"),
    (r"\bJACQUI\s*E\b", "Retail"),
    (r"\bCUE\b", "Retail"),
    (r"\bDECJUBA\b", "Retail"),
    (r"\bSHOWPO\b", "Retail"),
    (r"\bPRINCESS\s+POLLY\b", "Retail"),
    (r"\bWHITE\s+FOX\b", "Retail"),
    (r"\bCITY\s+BEACH\b", "Retail"),
    (r"\bSURF\s+STITCH\b", "Retail"),
    (r"\bSURF\s+DIVE\s+N\s+SKI\b", "Retail"),
    (r"\bRIP\s+CURL\b", "Retail"),
    (r"\bQUIKSILVER\b", "Retail"),
    (r"\bBILLABONG\b", "Retail"),
    (r"\bJAY\s+JAYS\b", "Retail"),
    (r"\bFACTORIE\b", "Retail"),
    (r"\bALLY\s+FASHION\b", "Retail"),
    (r"\bLULULEMON\b", "Retail"),
    (r"\bLULU\s+LEMON\b", "Retail"),
    (r"\bATHLETA\b", "Retail"),
    (r"\bNIKE\b", "Retail"),
    (r"\bADIDAS\b", "Retail"),
    (r"\bPUMA\b", "Retail"),
    (r"\bUNDER\s+ARMOUR\b", "Retail"),
    (r"\bREEBOK\b", "Retail"),
    (r"\bASICS\b", "Retail"),
    (r"\bNEW\s+BALANCE\b", "Retail"),
    (r"\bSKECHERS\b", "Retail"),
    (r"\bCONVERSE\b", "Retail"),
    (r"\bVANS\b", "Retail"),
    (r"\bFOOT\s+LOCKER\b", "Retail"),
    (r"\bJD\s+SPORTS\b", "Retail"),
    (r"\bPLATYPUS\s+SHOES\b", "Retail"),
    (r"\bHYPE\s*DC\b", "Retail"),
    (r"\bAQUILA\b", "Retail"),
    (r"\bWINDSOR\s+SMITH\b", "Retail"),
    (r"\bDIAMOND\s+BLADE\b", "Retail"),
    (r"\bBETTS\b", "Retail"),
    (r"\bWILLIAMS\s+SHOES\b", "Retail"),
    (r"\bNOVO\s+SHOES\b", "Retail"),
    (r"\bPANDORA\b", "Retail"),
    (r"\bMICHAEL\s+HILL\b", "Retail"),
    (r"\bPROUDS\b", "Retail"),
    (r"\bANGUS\s+AND\s+COOTE\b", "Retail"),
    (r"\bJEWELLER\b", "Retail"),
    (r"\bBED\s+BATH\s+N\s+TABLE\b", "Retail"),
    (r"\bAD AIRS\b", "Retail"),
    (r"\bHOUSE\b", "Retail"),
    (r"\bPILLOW\s+TALK\b", "Retail"),
    (r"\bSHERIDAN\b", "Retail"),
    (r"\bPROVINCIAL\s+HOME\b", "Retail"),
    (r"\bTEMPUR\b", "Retail"),
    (r"\bIKEA\b", "Home Improvement"),
    (r"\bHARVEY\s+NORMAN\b", "Retail"),
    (r"\bTHE\s+GOOD\s+GUYS\b", "Retail"),
    (r"\bBING\s+LEE\b", "Retail"),
    (r"\bBETTA\s+HOME\s+LIVING\b", "Retail"),
    (r"\bRETRAVISION\b", "Retail"),
    (r"\bAPPLIANCES\s+ONLINE\b", "Retail"),
    (r"\bBABY\s+BUNTING\b", "Retail"),
    (r"\bSPOTLIGHT\b", "Retail"),
    (r"\bLINCRAFT\b", "Retail"),
    (r"\bBCF\b", "Retail"),
    (r"\bANACONDA\b", "Retail"),
    (r"\bDECATHLON\b", "Retail"),
    (r"\bKATHMANDU\b", "Retail"),
    (r"\bMACPAC\b", "Retail"),
    (r"\bMOUNTAIN\s+DESIGNS\b", "Retail"),
    (r"\bPATAGONIA\b", "Retail"),
    (r"\bTHE\s+NORTH\s+FACE\b", "Retail"),
    (r"\bCOLUMBIA\s+SPORTSWEAR\b", "Retail"),
    (r"\bELECTRONICS\s+BOUTIQUE\b", "Retail"),
    (r"\bEB\s+GAMES\b", "Retail"),
    (r"\bZING\s+POP\s+CULTURE\b", "Retail"),
    (r"\bGAMESTOP\b", "Retail"),
    (r"\bCLOTHING\b", "Retail"),
    (r"\bFASHION\b", "Retail"),
    (r"\bAPPAREL\b", "Retail"),
    (r"\bFOOTWEAR\b", "Retail"),
    (r"\bSPORTSWEAR\b", "Retail"),
    (r"\bHOME\s*WARES?\b", "Retail"),
    (r"\bMANCHESTER\b", "Retail"),
    (r"\bHARDWARE\b", "Home Improvement"),
    (r"\bAMART\s+FURNITURE\b", "Retail"),
    (r"\bFANTASTIC\s+FURNITURE\b", "Retail"),
    (r"\bFURNITURE\b", "Retail"),
    (r"\bFREEDOM\s+FURNITURE\b", "Retail"),
    (r"\bNICK\s+SCALI\b", "Retail"),
    (r"\bKING\s+LIVING\b", "Retail"),
    (r"\bDOMAYNE\b", "Retail"),
    (r"\bFORTY\s+WINKS\b", "Retail"),
    (r"\bSNOOZE\b", "Retail"),
    (r"\bPETBARN\b", "Pet Care"),
    (r"\bPETSTOCK\b", "Pet Care"),
    (r"\bPET\s+CIRCLE\b", "Pet Care"),
    (r"\bBEST\s+FRIENDS\s+PET\b", "Pet Care"),
    (r"\bPET\s+SUPPLIES\b", "Pet Care"),
    (r"\bAQUARIUM\b", "Retail"),
    (r"\bPET\s+SHOP\b", "Pet Care"),
    (r"\bDOLLARAMA\b", "Department Stores"),
    # =========================================================================
    # Department Stores — big-box / variety
    # =========================================================================
    (r"\bKMART\b", "Department Stores"),
    (r"\bTARGET\s+AUSTRALIA\b", "Department Stores"),
    (r"\bTARGET\b", "Department Stores"),
    (r"\bBIG\s*W\b", "Department Stores"),
    (r"\bMYER\b", "Department Stores"),
    (r"\bDAVID\s+JONES\b", "Department Stores"),
    (r"\bBUNNINGS\b", "Home Improvement"),
    (r"\bCOSTCO\b", "Department Stores"),
    (r"\bBEST\s*&\s*LESS\b", "Department Stores"),
    (r"\bTHE\s+REJECT\s+SHOP\b", "Department Stores"),
    (r"\bREJECT\s+SHOP\b", "Department Stores"),
    (r"\bDOLLAR\s+KING\b", "Department Stores"),
    (r"\bDISCOUNT\s+VARIETY\b", "Department Stores"),
    (r"\bVARIETY\s+STORE\b", "Department Stores"),
    (r"\bDEPARTMENT\s+STORE\b", "Department Stores"),
    # =========================================================================
    # Home Improvement — hardware, building supplies, trades
    # =========================================================================
    (r"\bBUNNINGS\b", "Home Improvement"),
    (r"\bMITRE\s+10\b", "Home Improvement"),
    (r"\bHOME\s+HARDWARE\b", "Home Improvement"),
    (r"\bTHRIFTY\s+LINK\b", "Home Improvement"),
    (r"\bTRADE\s+LINK\b", "Home Improvement"),
    (r"\bREECE\s+PLUMBING\b", "Home Improvement"),
    (r"\bREECE\b", "Home Improvement"),
    (r"\bPLUMBING\b", "Home Improvement"),
    (r"\bTIMBER\b", "Home Improvement"),
    (r"\bHARDWARE\s+STORE\b", "Home Improvement"),
    (r"\bBUILDING\s+SUPPLIES\b", "Home Improvement"),
    (r"\bLANDSCAPE\s+SUPPLIES\b", "Home Improvement"),
    (r"\bGARDEN\s+SUPPLIES\b", "Home Improvement"),
    (r"\bNURSERY\b", "Home Improvement"),
    (r"\bPAINT\s+SHOP\b", "Home Improvement"),
    (r"\bCONCRETE\b", "Home Improvement"),
    (r"\bSTEEL\b", "Home Improvement"),
    (r"\bROOFING\b", "Home Improvement"),
    (r"\bFLOORING\b", "Home Improvement"),
    (r"\bTILING\b", "Home Improvement"),
    (r"\bELECTRICAL\s+SUPPLIES\b", "Home Improvement"),
    (r"\bSCAFFOLDING\b", "Home Improvement"),
    (r"\bCONSTRUCTION\b", "Home Improvement"),
    (r"\bRENOVATION\b", "Home Improvement"),
    # =========================================================================
    # Gyms and other memberships — fitness, gyms, sports, memberships
    # =========================================================================
    (r"\bGOODLIFE\s+HEALTH\b", "Gyms and other memberships"),
    (r"\bGOODLIFE\b", "Gyms and other memberships"),
    (r"\bANYTIME\s+FITNESS\b", "Gyms and other memberships"),
    (r"\bFITNESS\s+FIRST\b", "Gyms and other memberships"),
    (r"\bFITNESS\s+PASSPORT\b", "Gyms and other memberships"),
    (r"\bFITNESS\s+CARTEL\b", "Gyms and other memberships"),
    (r"\bJETTS\s+FITNESS\b", "Gyms and other memberships"),
    (r"\bJETTS\b", "Gyms and other memberships"),
    (r"\bF45\b", "Gyms and other memberships"),
    (r"\bSNAP\s+FITNESS\b", "Gyms and other memberships"),
    (r"\bPLUS\s+FITNESS\b", "Gyms and other memberships"),
    (r"\bZAP\s+FITNESS\b", "Gyms and other memberships"),
    (r"\bCLUB\s+LIME\b", "Gyms and other memberships"),
    (r"\bVIRGIN\s+ACTIVE\b", "Gyms and other memberships"),
    (r"\bFERNY\s+GYM\b", "Gyms and other memberships"),
    (r"\bWORLD\s+GYM\b", "Gyms and other memberships"),
    (r"\bREVOFIT\b", "Gyms and other memberships"),
    (r"\bCRUNCH\s+FITNESS\b", "Gyms and other memberships"),
    (r"\bCROSSFIT\b", "Gyms and other memberships"),
    (r"\bFITNESS\s+PLAYGROUND\b", "Gyms and other memberships"),
    (r"\bGENESIS\s+HEALTH\b", "Gyms and other memberships"),
    (r"\bNEXT\s+GEN\s+HEALTH\b", "Gyms and other memberships"),
    (r"\bURBAN\s+RECREATION\b", "Gyms and other memberships"),
    (r"\bPOWERHOUSE\b", "Gyms and other memberships"),
    (r"\bREDEFINE\b", "Gyms and other memberships"),
    (r"\bGYM\b", "Gyms and other memberships"),
    (r"\bFITNESS\b", "Gyms and other memberships"),
    (r"\bPILATES\b", "Gyms and other memberships"),
    (r"\bAQUATIC\s+CENTRE\b", "Gyms and other memberships"),
    (r"\bLEISURE\s+CENTRE\b", "Gyms and other memberships"),
    (r"\bRECREATION\s+CENTRE\b", "Gyms and other memberships"),
    (r"\bSWIM\s+CENTRE\b", "Gyms and other memberships"),
    (r"\bSWIMMING\s+POOL\b", "Gyms and other memberships"),
    (r"\bSPORTS\s+COMPLEX\b", "Gyms and other memberships"),
    (r"\bSPORT\s+AND\s+RECREATION\b", "Gyms and other memberships"),
    (r"\bGOLF\s+IN\s+THE\s+CITY\b", "Gyms and other memberships"),
    (r"\bGOLF\s+CLUB\b", "Gyms and other memberships"),
    (r"\bGOLFER\b", "Gyms and other memberships"),
    (r"\bGOLF\b", "Gyms and other memberships"),
    (r"\bFOOTBALL\s+AUSTRALIA\b", "Gyms and other memberships"),
    (r"\bFOOTBALL\s+CLUB\b", "Entertainment"),
    (r"\bFOOTBALL\b", "Gyms and other memberships"),
    (r"\bNETBALL\s+CLUB\b", "Gyms and other memberships"),
    (r"\bNETBALL\b", "Gyms and other memberships"),
    (r"\bCRICKET\s+CLUB\b", "Gyms and other memberships"),
    (r"\bBASKETBALL\s+CLUB\b", "Gyms and other memberships"),
    (r"\bBASKETBALL\b", "Gyms and other memberships"),
    (r"\bSOCCER\s+CLUB\b", "Gyms and other memberships"),
    (r"\bTENNIS\s+CLUB\b", "Gyms and other memberships"),
    (r"\bTENNIS\b", "Gyms and other memberships"),
    (r"\bSWIM\s+CLUB\b", "Gyms and other memberships"),
    (r"\bSQUASH\s+CLUB\b", "Gyms and other memberships"),
    (r"\bATHLETICS\s+CLUB\b", "Gyms and other memberships"),
    (r"\bMARTIAL\s+ARTS\b", "Gyms and other memberships"),
    (r"\bTAEKWONDO\b", "Gyms and other memberships"),
    (r"\bKARATE\b", "Gyms and other memberships"),
    (r"\bJIU\s*JITSU\b", "Gyms and other memberships"),
    (r"\bJUDO\b", "Gyms and other memberships"),
    (r"\bBOXING\b", "Gyms and other memberships"),
    (r"\bMUAY\s+THAI\b", "Gyms and other memberships"),
    (r"\bKICKBOXING\b", "Gyms and other memberships"),
    (r"\bMMA\b", "Gyms and other memberships"),
    (r"\bBRAZILIAN\s+JIU\b", "Gyms and other memberships"),
    (r"\bPERSONAL\s+TRAINER\b", "Gyms and other memberships"),
    (r"\bPERSONAL\s+TRAINING\b", "Gyms and other memberships"),
    (r"\bPT\s+SESSION\b", "Gyms and other memberships"),
    (r"\bPILATES\s+STUDIO\b", "Gyms and other memberships"),
    (r"\bCLUBLINKS\b", "Gyms and other memberships"),
    (r"\bSPORTS\s+MEDICINE\b", "Health"),
    # =========================================================================
    # Entertainment — cinemas, events, ticketing, attractions
    # =========================================================================
    (r"\bHOYTS\b", "Entertainment"),
    (r"\bEVENT\s+CINEMAS?\b", "Entertainment"),
    (r"\bREADING\s+CINEMAS?\b", "Entertainment"),
    (r"\bVILLAGE\s+CINEMAS?\b", "Entertainment"),
    (r"\bDENDY\s+CINEMAS?\b", "Entertainment"),
    (r"\bPALACE\s+CINEMAS?\b", "Entertainment"),
    (r"\bCINEMA\b", "Entertainment"),
    (r"\bTICKETEK\b", "Entertainment"),
    (r"\bTICKETMASTER\b", "Entertainment"),
    (r"\bMOSHTIX\b", "Entertainment"),
    (r"\bOZTIX\b", "Entertainment"),
    (r"\bEVENTBRITE\b", "Entertainment"),
    (r"\bTRYBOOKING\b", "Entertainment"),
    (r"\bSTICKYTICKETS\b", "Entertainment"),
    (r"\bAUSTRALIA\s+ZOO\b", "Entertainment"),
    (r"\bTARONGA\s+ZOO\b", "Entertainment"),
    (r"\bWERRIBEE\s+ZOO\b", "Entertainment"),
    (r"\bLUNA\s+PARK\b", "Entertainment"),
    (r"\bDREAMWORLD\b", "Entertainment"),
    (r"\bMOVIE\s+WORLD\b", "Entertainment"),
    (r"\bSEA\s+WORLD\b", "Entertainment"),
    (r"\bWET\s+N\s+WILD\b", "Entertainment"),
    (r"\bWARNER\s+BROS\b", "Entertainment"),
    (r"\bTHEME\s+PARK\b", "Entertainment"),
    (r"\bWATER\s+PARK\b", "Entertainment"),
    (r"\bAQUARIUM\b", "Entertainment"),
    (r"\bWILDLIFE\s+PARK\b", "Entertainment"),
    (r"\bMUSEUM\b", "Entertainment"),
    (r"\bART\s+GALLERY\b", "Entertainment"),
    (r"\bGALLERY\b", "Entertainment"),
    (r"\bBOWLING\b", "Entertainment"),
    (r"\bLASER\s+TAG\b", "Entertainment"),
    (r"\bESCAPE\s+ROOM\b", "Entertainment"),
    (r"\bKARAOKE\b", "Entertainment"),
    (r"\bARCADE\b", "Entertainment"),
    (r"\bPOOL\s+HALL\b", "Entertainment"),
    (r"\bAMUSEMENTS?\b", "Entertainment"),
    (r"\bSPYWILL\b", "Entertainment"),
    (r"\bFESTIVAL\b", "Entertainment"),
    (r"\bCONCERT\b", "Entertainment"),
    (r"\bSTADIUM\b", "Entertainment"),
    (r"\bTHEATRE\b", "Entertainment"),
    (r"\bTHEATER\b", "Entertainment"),
    (r"\bOPERA\s+HOUSE\b", "Entertainment"),
    (r"\bOPERA\b", "Entertainment"),
    (r"\bBALLET\b", "Entertainment"),
    (r"\bORCHESTRA\b", "Entertainment"),
    (r"\bSYMPHONY\b", "Entertainment"),
    (r"\bHOLEY\s+MOLEY\b", "Entertainment"),
    (r"\bARCHIE\s+BROTHERS\b", "Entertainment"),
    (r"\bSTRIKE\s+BOWLING\b", "Entertainment"),
    (r"\bTIMEZONE\b", "Entertainment"),
    (r"\bIPLAY\b", "Entertainment"),
    (r"\bPLAY\s+NOW\b", "Entertainment"),
    (r"\bINDOOR\s+PLAY\b", "Entertainment"),
    (r"\bTRAMPOLINE\b", "Entertainment"),
    (r"\bFLIP\s+OUT\b", "Entertainment"),
    (r"\bBOUNCE\s+INC\b", "Entertainment"),
    (r"\bSKY\s+ZONE\b", "Entertainment"),
    (r"\bGO\s*CART\b", "Entertainment"),
    (r"\bMINI\s+GOLF\b", "Entertainment"),
    (r"\bPUTT\s+PUTT\b", "Entertainment"),
    (r"\bPAINTBALL\b", "Entertainment"),
    (r"\bEVERYPAY\b", "Entertainment"),
    (r"\bPENRITH\s+RSL\b", "Entertainment"),
    (r"\bRACECOURSE\b", "Entertainment"),
    (r"\bCASINO\b", "Entertainment"),
    (r"\bRACING\s+CLUB\b", "Entertainment"),
    (r"\bRUGBY\s+LEAGUE\b", "Entertainment"),
    # =========================================================================
    # Personal Care — hair, beauty, nails, barber
    # =========================================================================
    (r"\bHAIRDRESSER\b", "Personal Care"),
    (r"\bHAIR\s+DRESSER\b", "Personal Care"),
    (r"\bHAIR\s+SALON\b", "Personal Care"),
    (r"\bHAIR\s+STUDIO\b", "Personal Care"),
    (r"\bHAIR\s+DESIGN\b", "Personal Care"),
    (r"\bHAIRMASTERS\b", "Personal Care"),
    (r"\bJUST\s+CUTS\b", "Personal Care"),
    (r"\bBARBER\b", "Personal Care"),
    (r"\bBEAUTY\s+SALON\b", "Personal Care"),
    (r"\bBEAUTY\s+STUDIO\b", "Personal Care"),
    (r"\bBEAUTY\s+THERAPY\b", "Personal Care"),
    (r"\bBEAUTY\s+SPA\b", "Personal Care"),
    (r"\bBEAUTY\b", "Personal Care"),
    (r"\bNAIL\s+SALON\b", "Personal Care"),
    (r"\bNAIL\s+BAR\b", "Personal Care"),
    (r"\bNAIL\s+STUDIO\b", "Personal Care"),
    (r"\bNAILS\b", "Personal Care"),
    (r"\bMANICURE\b", "Personal Care"),
    (r"\bPEDICURE\b", "Personal Care"),
    (r"\bWAXING\b", "Personal Care"),
    (r"\bTHREADING\b", "Personal Care"),
    (r"\bLASH\s+BAR\b", "Personal Care"),
    (r"\bLASHES\b", "Personal Care"),
    (r"\bEYELASH\b", "Personal Care"),
    (r"\bBROW\s+BAR\b", "Personal Care"),
    (r"\bTATTOO\b", "Personal Care"),
    (r"\bPIERCING\b", "Personal Care"),
    (r"\bMASSAGE\s+THERAPY\b", "Personal Care"),
    (r"\bDAY\s+SPA\b", "Personal Care"),
    (r"\bSPA\b", "Personal Care"),
    (r"\bTANNING\b", "Personal Care"),
    (r"\bSOLARIUM\b", "Personal Care"),
    (r"\bFRAGRANCE\b", "Personal Care"),
    (r"\bCOSMETICS\b", "Personal Care"),
    (r"\bMAKE\s*UP\b", "Personal Care"),
    (r"\bMAKEUP\b", "Personal Care"),
    (r"\bSKIN\s+CARE\b", "Personal Care"),
    (r"\bSKINCARE\b", "Personal Care"),
    (r"\bBODYLABS\b", "Personal Care"),
    (r"\bS AND CO\s+HAIR\b", "Personal Care"),
    (r"\bPROFESSIONAIL\b", "Personal Care"),
    (r"\bLANCOZE\b", "Personal Care"),
    (r"\bBLCK\s+BRWN\b", "Personal Care"),
    # =========================================================================
    # Donations / Charity
    # =========================================================================
    (r"\bDONATION\b", "Donations"),
    (r"\bDONATE\b", "Donations"),
    (r"\bCHARITY\b", "Donations"),
    (r"\bSALVATION\s+ARMY\b", "Donations"),
    (r"\bRED\s+CROSS\b", "Donations"),
    (r"\bST\s+VINCENT\s+DE\s+PAUL\b", "Donations"),
    (r"\bVINNIES\b", "Donations"),
    (r"\bRSPCA\b", "Donations"),
    (r"\bWORLD\s+VISION\b", "Donations"),
    (r"\bUNICEF\b", "Donations"),
    (r"\bOXFAM\b", "Donations"),
    (r"\bCANCER\s+COUNCIL\b", "Donations"),
    (r"\bBEYOND\s+BLUE\b", "Donations"),
    (r"\bLIFELINE\b", "Donations"),
    (r"\bFRED\s+HOLLOWS\b", "Donations"),
    (r"\bMSF\b", "Donations"),
    (r"\bDOCTORS\s+WITHOUT\b", "Donations"),
    (r"\bGREENPEACE\b", "Donations"),
    (r"\bWWF\b", "Donations"),
    (r"\bAMNESTY\b", "Donations"),
    (r"\bCATHOLIC\s+DIOCESE\b", "Donations"),
    (r"\bCHURCH\b", "Donations"),
    (r"\bMOSQUE\b", "Donations"),
    (r"\bTEMPLE\b", "Donations"),
    (r"\bSYNAGOGUE\b", "Donations"),
    (r"\bGO\s+FUND\s+ME\b", "Donations"),
    (r"\bCROWD\s*FUNDING\b", "Donations"),
    (r"\bSPONSOR\b", "Donations"),
    (r"\bFUNDRAISING\b", "Donations"),
    # =========================================================================
    # Pet Care — vets, pet supplies, grooming
    # =========================================================================
    (r"\bVETERINARY\b", "Pet Care"),
    (r"\bVET\s+CLINIC\b", "Pet Care"),
    (r"\bVET\s+HOSPITAL\b", "Pet Care"),
    (r"\bANIMAL\s+HOSPITAL\b", "Pet Care"),
    (r"\bPET\s+HOSPITAL\b", "Pet Care"),
    (r"\bPETBARN\b", "Pet Care"),
    (r"\bPETSTOCK\b", "Pet Care"),
    (r"\bPET\s+SUPPLIES\b", "Pet Care"),
    (r"\bPET\s+CIRCLE\b", "Pet Care"),
    (r"\bBEST\s+FRIENDS\s+PET\b", "Pet Care"),
    (r"\bPET\s+SHOP\b", "Pet Care"),
    (r"\bPET\s+FOOD\b", "Pet Care"),
    (r"\bDOG\s+GROOMING\b", "Pet Care"),
    (r"\bPET\s+GROOMING\b", "Pet Care"),
    (r"\bDOG\s+WASH\b", "Pet Care"),
    (r"\bPET\s+SITTING\b", "Pet Care"),
    (r"\bDOG\s+WALK\b", "Pet Care"),
    (r"\bPET\s+CARE\b", "Pet Care"),
    (r"\bGOLDEN\s+REINS\b", "Pet Care"),
    (r"\bANIMAL\s+FEED\b", "Pet Care"),
    (r"\bPET\s+STORE\b", "Pet Care"),
    (r"\bPET\s+WAREHOUSE\b", "Pet Care"),
    (r"\bEQUINE\b", "Pet Care"),
    (r"\bEQUESTRIAN\b", "Pet Care"),
    (r"\bHORSE\s+FEED\b", "Pet Care"),
    # =========================================================================
    # Education — schools, universities, training
    # =========================================================================
    (r"\bUNIVERSITY\b", "Education"),
    (r"\bUNI\b", "Education"),
    (r"\bTAFE\b", "Education"),
    (r"\bCOLLEGE\b", "Education"),
    (r"\bHIGH\s+SCHOOL\b", "Education"),
    (r"\bSECONDARY\s+SCHOOL\b", "Education"),
    (r"\bPRIMARY\s+SCHOOL\b", "Education"),
    (r"\bPUBLIC\s+SCHOOL\b", "Education"),
    (r"\bGRAMMAR\s+SCHOOL\b", "Education"),
    (r"\bCHRISTIAN\s+SCHOOL\b", "Education"),
    (r"\bCATHOLIC\s+SCHOOL\b", "Education"),
    (r"\bSCHOOL\b", "Education"),
    (r"\bCOLLEGE\b", "Education"),
    (r"\bFLEXISCHOOL\b", "Education"),
    (r"\bCHILDCARE\b", "Education"),
    (r"\bCHILD\s+CARE\b", "Education"),
    (r"\bDAYCARE\b", "Education"),
    (r"\bEARLY\s+LEARNING\b", "Education"),
    (r"\bKINDERGARTEN\b", "Education"),
    (r"\bPRESCHOOL\b", "Education"),
    (r"\bPRE[ -]?SCHOOL\b", "Education"),
    (r"\bTUTORING\b", "Education"),
    (r"\bTUTOR\b", "Education"),
    (r"\bTRAINING\s+INSTITUTE\b", "Education"),
    (r"\bCOLLEGE\b", "Education"),
    (r"\bACADEMY\b", "Education"),
    (r"\bEDUCATION\s+CENTRE\b", "Education"),
    (r"\bEDUCATION\b", "Education"),
    (r"\bLEARNING\s+CENTRE\b", "Education"),
    (r"\bSTUDENT\b", "Education"),
    (r"\bSCHOOL\s+OF\b", "Education"),
    (r"\bINSTITUTE\b", "Education"),
    (r"\bTAFE\s+NSW\b", "Education"),
    (r"\bTAFE\s+QLD\b", "Education"),
    (r"\bTAFE\s+SA\b", "Education"),
    (r"\bTAFE\s+WA\b", "Education"),
    (r"\bTAFE\s+VIC\b", "Education"),
    (r"\bTAFE\s+TAS\b", "Education"),
    (r"\bRMIT\b", "Education"),
    (r"\bMONASH\b", "Education"),
    (r"\bDEAKIN\b", "Education"),
    (r"\bLATROBE\b", "Education"),
    (r"\bSWINBURNE\b", "Education"),
    (r"\bMELBOURNE\s+UNI\b", "Education"),
    (r"\bSYDNEY\s+UNI\b", "Education"),
    (r"\bUNSW\b", "Education"),
    (r"\bUTS\b", "Education"),
    (r"\bMACQUARIE\s+UNI\b", "Education"),
    (r"\bQUT\b", "Education"),
    (r"\bGRIFFITH\s+UNI\b", "Education"),
    (r"\bUQ\b", "Education"),
    (r"\bUSC\b", "Education"),
    (r"\bJCU\b", "Education"),
    (r"\bCQU\b", "Education"),
    (r"\bUNE\b", "Education"),
    (r"\bCSU\b", "Education"),
    (r"\bUOW\b", "Education"),
    (r"\bNEWCASTLE\s+UNI\b", "Education"),
    (r"\bCUTIN\b", "Education"),
    (r"\bMURDOCH\s+UNI\b", "Education"),
    (r"\bECU\b", "Education"),
    (r"\bFLINDERS\s+UNI\b", "Education"),
    (r"\bUNISA\b", "Education"),
    (r"\bADELAIDE\s+UNI\b", "Education"),
    (r"\bUTAS\b", "Education"),
    (r"\bCDU\b", "Education"),
    (r"\bAN\b", "Education"),
    # =========================================================================
    # Rent — residential and commercial rent payments
    # =========================================================================
    (r"\bRENT\s+PAYMENT\b", "Rent"),
    (r"\bRENTAL\s+PAYMENT\b", "Rent"),
    (r"\bRENT\b", "Rent"),
    (r"\bREAL\s+ESTATE\s+AGENCY\b", "Rent"),
    (r"\bLJ\s+HOOKER\b", "Rent"),
    (r"\bRAY\s+WHITE\b", "Rent"),
    (r"\bMCGRATH\s+REAL\b", "Rent"),
    (r"\bBELLE\s+PROPERTY\b", "Rent"),
    (r"\bHOCKINGSTUART\b", "Rent"),
    (r"\bBARRY\s+PLANT\b", "Rent"),
    (r"\bCENTURY\s+21\b", "Rent"),
    (r"\bELDERS\s+REAL\b", "Rent"),
    (r"\bFIRST\s+NATIONAL\s+REAL\b", "Rent"),
    (r"\bPRD\s+NATIONWIDE\b", "Rent"),
    (r"\bPROPERTY\s+MANAGEMENT\b", "Rent"),
    (r"\bSTRATA\s+LEVY\b", "Rent"),
    (r"\bBODY\s+CORPORATE\b", "Rent"),
    (r"\bLANDLORD\b", "Rent"),
    (r"\bTENANCY\b", "Rent"),
    # =========================================================================
    # Information — services, consulting, professional
    # =========================================================================
    (r"\bCONSULTING\b", "Information"),
    (r"\bCONSULTANCY\b", "Information"),
    (r"\bCONSULTANTS?\b", "Information"),
    (r"\bACCOUNTING\b", "Information"),
    (r"\bACCOUNTANTS?\b", "Information"),
    (r"\bSOLICITOR\b", "Information"),
    (r"\bLAWYER\b", "Information"),
    (r"\bLEGAL\s+SERVICES\b", "Information"),
    (r"\bTAX\s+AGENT\b", "Information"),
    (r"\bTAX\s+RETURN\b", "Information"),
    (r"\bBOOKKEEPING\b", "Information"),
    (r"\bFINANCIAL\s+PLAN\b", "Information"),
    (r"\bFINANCIAL\s+ADVIS\b", "Information"),
    (r"\bMORTGAGE\s+BROKER\b", "Information"),
    (r"\bSURVEYOR\b", "Information"),
    (r"\bARCHITECT\b", "Information"),
    (r"\bENGINEERING\b", "Information"),
    (r"\bRECRUITMENT\b", "Information"),
    (r"\bEMPLOYMENT\b", "Information"),
    (r"\bSTAFFING\b", "Information"),
    (r"\bLABOUR\s+HIRE\b", "Information"),
    (r"\bCLEANING\s+SERVICE\b", "Information"),
    (r"\bSECURITY\s+SERVICE\b", "Information"),
    (r"\bMARKETING\b", "Information"),
    (r"\bADVERTISING\b", "Information"),
    (r"\bGRAPHIC\s+DESIGN\b", "Information"),
    (r"\bWEB\s+DESIGN\b", "Information"),
    (r"\bIT\s+SERVICES\b", "Information"),
    (r"\bSOFTWARE\b", "Information"),
    (r"\bPRINTING\b", "Information"),
    (r"\bPHOTOGRAPHY\b", "Information"),
    (r"\bTRANSLATION\b", "Information"),
    (r"\bINTERPRETING\b", "Information"),
    (r"\bNOTARY\b", "Information"),
    (r"\bCONVEYANCING\b", "Information"),
    (r"\bSETTLEMENT\s+AGENT\b", "Information"),
    (r"\bINFORMATION\s+TECH\b", "Information"),
    (r"\bDATA\s+SERVICE\b", "Information"),
    (r"\bBUSINESS\s+SERVICE\b", "Information"),
    (r"\bPROFESSIONAL\s+SERVICE\b", "Information"),
]

# Patterns that override the general "Dining Out" -> "Entertainment" mapping
# when the matched merchant is clearly a sports/entertainment venue.
# Also used to refine other tentative classifications (e.g. Gyms → Entertainment).
ENTERTAINMENT_REFINEMENT: list[tuple[str, str]] = [
    (r"\bRUGBY\s+LEAGUE\b", "Entertainment"),
    (r"\bFOOTBALL\s+CLUB\b", "Entertainment"),
    (r"\bRACECOURSE\b", "Entertainment"),
    (r"\bCASINO\b", "Entertainment"),
    (r"\bCINEMA\b", "Entertainment"),
    (r"\bHOYTS\b", "Entertainment"),
    (r"\bEVENT\b", "Entertainment"),
    (r"\bTICKET\b", "Entertainment"),
    (r"\bTICKETEK\b", "Entertainment"),
    (r"\bTICKETMASTER\b", "Entertainment"),
    (r"\bMOSHTIX\b", "Entertainment"),
    (r"\bCONCERT\b", "Entertainment"),
    (r"\bTHEATRE\b", "Entertainment"),
    (r"\bTHEATER\b", "Entertainment"),
    (r"\bSTADIUM\b", "Entertainment"),
    (r"\bAMUSEMENT\b", "Entertainment"),
    (r"\bZOO\b", "Entertainment"),
    (r"\bAQUARIUM\b", "Entertainment"),
    (r"\bTHEME\s+PARK\b", "Entertainment"),
    (r"\bBOWLING\b", "Entertainment"),
    (r"\bFESTIVAL\b", "Entertainment"),
    (r"\bMUSEUM\b", "Entertainment"),
    (r"\bGALLERY\b", "Entertainment"),
    (r"\bKARAOKE\b", "Entertainment"),
    (r"\bLASER\s+TAG\b", "Entertainment"),
    (r"\bESCAPE\s+ROOM\b", "Entertainment"),
    (r"\bARCADE\b", "Entertainment"),
    (r"\bOPERA\b", "Entertainment"),
    (r"\bBALLET\b", "Entertainment"),
]


# ── Pre-compiled fallback regexes (category → compiled pattern) ─────────
# Grouping by category and compiling a single |-alternated regex per category
# cuts per-row regex searches from ~1,119 to ~22 — a ~50× speedup for the
# fallback classify step (which runs on ~11,000 NaN rows).
#
# Category order is preserved from _FALLBACK_RULES (first-match-wins).
# Each category's patterns are joined with `|`; longer/more-specific patterns
# are placed first within each group so they take priority in alternation.

def _build_compiled_fallback(
    rules: list[tuple[str, str]],
) -> list[tuple[str, "re.Pattern"]]:
    """Compile fallback rules grouped by category, preserving first-match order."""
    from collections import OrderedDict

    grouped: OrderedDict[str, list[str]] = OrderedDict()
    for pattern, cat in rules:
        grouped.setdefault(cat, []).append(pattern)

    compiled: list[tuple[str, "re.Pattern"]] = []
    for cat, patterns in grouped.items():
        # Sort by length descending so longer patterns match before shorter ones
        # within the same category (avoids e.g. "BAR AND GRILL" being missed
        # because "BAR" matched first inside the alternation).
        patterns_sorted = sorted(patterns, key=lambda p: -len(p))
        combined = "|".join(patterns_sorted)  # noqa: E501
        compiled.append((cat, re.compile(combined)))
    return compiled


COMPILED_FALLBACK = _build_compiled_fallback(FALLBACK_RULES)
COMPILED_ENT_REFINEMENT = _build_compiled_fallback(ENTERTAINMENT_REFINEMENT)
